exports.languages = {
    "apl":{name: "APL", mime: "text/apl", mode: "apl", ext: ["dyalog", "apl"]},
    "pgp":{name: "PGP", mimes: ["application/pgp", "application/pgp-keys", "application/pgp-signature"], mode: "asciiarmor", ext: ["pgp"]},
    "asn.1":{name: "ASN.1", mime: "text/x-ttcn-asn", mode: "asn.1", ext: ["asn", "asn1"]},
    "asterisk":{name: "Asterisk", mime: "text/x-asterisk", mode: "asterisk", file: /^extensions\.conf$/i},
    "brainfuck":{name: "Brainfuck", mime: "text/x-brainfuck", mode: "brainfuck", ext: ["b", "bf"]},
    "c":{name: "C", mime: "text/x-csrc", mode: "clike", ext: ["c", "h"]},
    "c++":{name: "C++", mime: "text/x-c++src", mode: "clike", ext: ["cpp", "c++", "cc", "cxx", "hpp", "h++", "hh", "hxx"], alias: ["cpp"]},
    "cobol":{name: "Cobol", mime: "text/x-cobol", mode: "cobol", ext: ["cob", "cpy"]},
    "c#":{name: "C#", mime: "text/x-csharp", mode: "clike", ext: ["cs"], alias: ["csharp"]},
    "clojure":{name: "Clojure", mime: "text/x-clojure", mode: "clojure", ext: ["clj"]},
    "clojurescript":{name: "ClojureScript", mime: "text/x-clojurescript", mode: "clojure", ext: ["cljs"]},
    "closure stylesheets (gss)":{name: "Closure Stylesheets (GSS)", mime: "text/x-gss", mode: "css", ext: ["gss"]},
    "cmake":{name: "CMake", mime: "text/x-cmake", mode: "cmake", ext: ["cmake", "cmake.in"], file: /^CMakeLists.txt$/},
    "coffeescript":{name: "CoffeeScript", mime: "text/x-coffeescript", mode: "coffeescript", ext: ["coffee"], alias: ["coffee", "coffee-script"]},
    "common lisp":{name: "Common Lisp", mime: "text/x-common-lisp", mode: "commonlisp", ext: ["cl", "lisp", "el"], alias: ["lisp"]},
    "cypher":{name: "Cypher", mime: "application/x-cypher-query", mode: "cypher", ext: ["cyp", "cypher"]},
    "cython":{name: "Cython", mime: "text/x-cython", mode: "python", ext: ["pyx", "pxd", "pxi"]},
    "crystal":{name: "Crystal", mime: "text/x-crystal", mode: "crystal", ext: ["cr"]},
    "css":{name: "CSS", mime: "text/css", mode: "css", ext: ["css"]},
    "cql":{name: "CQL", mime: "text/x-cassandra", mode: "sql", ext: ["cql"]},
    "d":{name: "D", mime: "text/x-d", mode: "d", ext: ["d"]},
    "dart":{name: "Dart", mimes: ["application/dart", "text/x-dart"], mode: "dart", ext: ["dart"]},
    "diff":{name: "diff", mime: "text/x-diff", mode: "diff", ext: ["diff", "patch"]},
    "django":{name: "Django", mime: "text/x-django", mode: "django"},
    "dockerfile":{name: "Dockerfile", mime: "text/x-dockerfile", mode: "dockerfile", file: /^Dockerfile$/},
    "dtd":{name: "DTD", mime: "application/xml-dtd", mode: "dtd", ext: ["dtd"]},
    "dylan":{name: "Dylan", mime: "text/x-dylan", mode: "dylan", ext: ["dylan", "dyl", "intr"]},
    "ebnf":{name: "EBNF", mime: "text/x-ebnf", mode: "ebnf"},
    "ecl":{name: "ECL", mime: "text/x-ecl", mode: "ecl", ext: ["ecl"]},
    "eiffel":{name: "Eiffel", mime: "text/x-eiffel", mode: "eiffel", ext: ["e"]},
    "elm":{name: "Elm", mime: "text/x-elm", mode: "elm", ext: ["elm"]},
    "embedded javascript":{name: "Embedded Javascript", mime: "application/x-ejs", mode: "htmlembedded", ext: ["ejs"]},
    "embedded ruby":{name: "Embedded Ruby", mime: "application/x-erb", mode: "htmlembedded", ext: ["erb"]},
    "erlang":{name: "Erlang", mime: "text/x-erlang", mode: "erlang", ext: ["erl"]},
    "factor":{name: "Factor", mime: "text/x-factor", mode: "factor", ext: ["factor"]},
    "fcl":{name: "FCL", mime: "text/x-fcl", mode: "fcl"},
    "forth":{name: "Forth", mime: "text/x-forth", mode: "forth", ext: ["forth", "fth", "4th"]},
    "fortran":{name: "Fortran", mime: "text/x-fortran", mode: "fortran", ext: ["f", "for", "f77", "f90"]},
    "f#":{name: "F#", mime: "text/x-fsharp", mode: "mllike", ext: ["fs"], alias: ["fsharp"]},
    "gas":{name: "Gas", mime: "text/x-gas", mode: "gas", ext: ["s"]},
    "gherkin":{name: "Gherkin", mime: "text/x-feature", mode: "gherkin", ext: ["feature"]},
    "github flavored markdown":{name: "GitHub Flavored Markdown", mime: "text/x-gfm", mode: "gfm", file: /^(readme|contributing|history).md$/i},
    "go":{name: "Go", mime: "text/x-go", mode: "go", ext: ["go"]},
    "groovy":{name: "Groovy", mime: "text/x-groovy", mode: "groovy", ext: ["groovy", "gradle"]},
    "haml":{name: "HAML", mime: "text/x-haml", mode: "haml", ext: ["haml"]},
    "haskell":{name: "Haskell", mime: "text/x-haskell", mode: "haskell", ext: ["hs"]},
    "haskell (literate)":{name: "Haskell (Literate)", mime: "text/x-literate-haskell", mode: "haskell-literate", ext: ["lhs"]},
    "haxe":{name: "Haxe", mime: "text/x-haxe", mode: "haxe", ext: ["hx"]},
    "hxml":{name: "HXML", mime: "text/x-hxml", mode: "haxe", ext: ["hxml"]},
    "asp.net":{name: "ASP.NET", mime: "application/x-aspx", mode: "htmlembedded", ext: ["aspx"], alias: ["asp", "aspx"]},
    "html":{name: "HTML", mime: "text/html", mode: "htmlmixed", ext: ["html", "htm"], alias: ["xhtml"]},
    "http":{name: "HTTP", mime: "message/http", mode: "http"},
    "idl":{name: "IDL", mime: "text/x-idl", mode: "idl", ext: ["pro"]},
    "jade":{name: "Jade", mime: "text/x-jade", mode: "jade", ext: ["jade"]},
    "java":{name: "Java", mime: "text/x-java", mode: "clike", ext: ["java"]},
    "java server pages":{name: "Java Server Pages", mime: "application/x-jsp", mode: "htmlembedded", ext: ["jsp"], alias: ["jsp"]},
    "javascript":{name: "JavaScript", mimes: ["text/javascript", "text/ecmascript", "application/javascript", "application/x-javascript", "application/ecmascript"], mode: "javascript", ext: ["js"], alias: ["ecmascript", "js", "node"]},
    "json":{name: "JSON", mimes: ["application/json", "application/x-json"], mode: "javascript", ext: ["json", "map"], alias: ["json5"]},
    "json-ld":{name: "JSON-LD", mime: "application/ld+json", mode: "javascript", ext: ["jsonld"], alias: ["jsonld"]},
    "jsx":{name: "JSX", mime: "text/jsx", mode: "jsx", ext: ["jsx"]},
    "jinja2":{name: "Jinja2", mime: "null", mode: "jinja2"},
    "julia":{name: "Julia", mime: "text/x-julia", mode: "julia", ext: ["jl"]},
    "kotlin":{name: "Kotlin", mime: "text/x-kotlin", mode: "clike", ext: ["kt"]},
    "less":{name: "LESS", mime: "text/x-less", mode: "css", ext: ["less"]},
    "livescript":{name: "LiveScript", mime: "text/x-livescript", mode: "livescript", ext: ["ls"], alias: ["ls"]},
    "lua":{name: "Lua", mime: "text/x-lua", mode: "lua", ext: ["lua"]},
    "markdown":{name: "Markdown", mime: "text/x-markdown", mode: "markdown", ext: ["markdown", "md", "mkd"]},
    "mirc":{name: "mIRC", mime: "text/mirc", mode: "mirc"},
    "mariadb sql":{name: "MariaDB SQL", mime: "text/x-mariadb", mode: "sql"},
    "mathematica":{name: "Mathematica", mime: "text/x-mathematica", mode: "mathematica", ext: ["m", "nb"]},
    "modelica":{name: "Modelica", mime: "text/x-modelica", mode: "modelica", ext: ["mo"]},
    "mumps":{name: "MUMPS", mime: "text/x-mumps", mode: "mumps"},
    "ms sql":{name: "MS SQL", mime: "text/x-mssql", mode: "sql"},
    "mysql":{name: "MySQL", mime: "text/x-mysql", mode: "sql"},
    "nginx":{name: "Nginx", mime: "text/x-nginx-conf", mode: "nginx", file: /nginx.*\.conf$/i},
    "nsis":{name: "NSIS", mime: "text/x-nsis", mode: "nsis", ext: ["nsh", "nsi"]},
    "ntriples":{name: "NTriples", mime: "text/n-triples", mode: "ntriples", ext: ["nt"]},
    "objective c":{name: "Objective C", mime: "text/x-objectivec", mode: "clike", ext: ["m", "mm"]},
    "ocaml":{name: "OCaml", mime: "text/x-ocaml", mode: "mllike", ext: ["ml", "mli", "mll", "mly"]},
    "octave":{name: "Octave", mime: "text/x-octave", mode: "octave", ext: ["m"]},
    "oz":{name: "Oz", mime: "text/x-oz", mode: "oz", ext: ["oz"]},
    "pascal":{name: "Pascal", mime: "text/x-pascal", mode: "pascal", ext: ["p", "pas"]},
    "peg.js":{name: "PEG.js", mime: "null", mode: "pegjs", ext: ["jsonld"]},
    "perl":{name: "Perl", mime: "text/x-perl", mode: "perl", ext: ["pl", "pm"]},
    "php":{name: "PHP", mime: "application/x-httpd-php", mode: "php", ext: ["php", "php3", "php4", "php5", "phtml"]},
    "pig":{name: "Pig", mime: "text/x-pig", mode: "pig", ext: ["pig"]},
    "plain text":{name: "Plain Text", mime: "text/plain", mode: "null", ext: ["txt", "text", "conf", "def", "list", "log"]},
    "plsql":{name: "PLSQL", mime: "text/x-plsql", mode: "sql", ext: ["pls"]},
    "properties files":{name: "Properties files", mime: "text/x-properties", mode: "properties", ext: ["properties", "ini", "in"], alias: ["ini", "properties"]},
    "python":{name: "Python", mime: "text/x-python", mode: "python", ext: ["py", "pyw"]},
    "puppet":{name: "Puppet", mime: "text/x-puppet", mode: "puppet", ext: ["pp"]},
    "q":{name: "Q", mime: "text/x-q", mode: "q", ext: ["q"]},
    "r":{name: "R", mime: "text/x-rsrc", mode: "r", ext: ["r"], alias: ["rscript"]},
    "restructuredtext":{name: "reStructuredText", mime: "text/x-rst", mode: "rst", ext: ["rst"], alias: ["rst"]},
    "rpm changes":{name: "RPM Changes", mime: "text/x-rpm-changes", mode: "rpm"},
    "rpm spec":{name: "RPM Spec", mime: "text/x-rpm-spec", mode: "rpm", ext: ["spec"]},
    "ruby":{name: "Ruby", mime: "text/x-ruby", mode: "ruby", ext: ["rb"], alias: ["jruby", "macruby", "rake", "rb", "rbx"]},
    "rust":{name: "Rust", mime: "text/x-rustsrc", mode: "rust", ext: ["rs"]},
    "sass":{name: "Sass", mime: "text/x-sass", mode: "sass", ext: ["sass"]},
    "scala":{name: "Scala", mime: "text/x-scala", mode: "clike", ext: ["scala"]},
    "scheme":{name: "Scheme", mime: "text/x-scheme", mode: "scheme", ext: ["scm", "ss"]},
    "scss":{name: "SCSS", mime: "text/x-scss", mode: "css", ext: ["scss"]},
    "shell":{name: "Shell", mime: "text/x-sh", mode: "shell", ext: ["sh", "ksh", "bash"], alias: ["bash", "sh", "zsh"], file: /^PKGBUILD$/},
    "sieve":{name: "Sieve", mime: "application/sieve", mode: "sieve", ext: ["siv", "sieve"]},
    "slim":{name: "Slim", mimes: ["text/x-slim", "application/x-slim"], mode: "slim", ext: ["slim"]},
    "smalltalk":{name: "Smalltalk", mime: "text/x-stsrc", mode: "smalltalk", ext: ["st"]},
    "smarty":{name: "Smarty", mime: "text/x-smarty", mode: "smarty", ext: ["tpl"]},
    "solr":{name: "Solr", mime: "text/x-solr", mode: "solr"},
    "soy":{name: "Soy", mime: "text/x-soy", mode: "soy", ext: ["soy"], alias: ["closure template"]},
    "sparql":{name: "SPARQL", mime: "application/sparql-query", mode: "sparql", ext: ["rq", "sparql"], alias: ["sparul"]},
    "spreadsheet":{name: "Spreadsheet", mime: "text/x-spreadsheet", mode: "spreadsheet", alias: ["excel", "formula"]},
    "sql":{name: "SQL", mime: "text/x-sql", mode: "sql", ext: ["sql"]},
    "squirrel":{name: "Squirrel", mime: "text/x-squirrel", mode: "clike", ext: ["nut"]},
    "swift":{name: "Swift", mime: "text/x-swift", mode: "swift", ext: ["swift"]},
    "mariadb":{name: "MariaDB", mime: "text/x-mariadb", mode: "sql"},
    "stex":{name: "sTeX", mime: "text/x-stex", mode: "stex"},
    "latex":{name: "LaTeX", mime: "text/x-latex", mode: "stex", ext: ["text", "ltx"], alias: ["tex"]},
    "systemverilog":{name: "SystemVerilog", mime: "text/x-systemverilog", mode: "verilog", ext: ["v"]},
    "tcl":{name: "Tcl", mime: "text/x-tcl", mode: "tcl", ext: ["tcl"]},
    "textile":{name: "Textile", mime: "text/x-textile", mode: "textile", ext: ["textile"]},
    "tiddlywiki ":{name: "TiddlyWiki ", mime: "text/x-tiddlywiki", mode: "tiddlywiki"},
    "tiki wiki":{name: "Tiki wiki", mime: "text/tiki", mode: "tiki"},
    "toml":{name: "TOML", mime: "text/x-toml", mode: "toml", ext: ["toml"]},
    "tornado":{name: "Tornado", mime: "text/x-tornado", mode: "tornado"},
    "troff":{name: "troff", mime: "troff", mode: "troff", ext: ["1", "2", "3", "4", "5", "6", "7", "8", "9"]},
    "ttcn":{name: "TTCN", mime: "text/x-ttcn", mode: "ttcn", ext: ["ttcn", "ttcn3", "ttcnpp"]},
    "ttcn_cfg":{name: "TTCN_CFG", mime: "text/x-ttcn-cfg", mode: "ttcn-cfg", ext: ["cfg"]},
    "turtle":{name: "Turtle", mime: "text/turtle", mode: "turtle", ext: ["ttl"]},
    "typescript":{name: "TypeScript", mime: "application/typescript", mode: "javascript", ext: ["ts"], alias: ["ts"]},
    "twig":{name: "Twig", mime: "text/x-twig", mode: "twig"},
    "vb.net":{name: "VB.NET", mime: "text/x-vb", mode: "vb", ext: ["vb"]},
    "vbscript": {name: "VBScript", mime: "text/vbscript", mode: "vbscript", ext: ["vbs"]},
    "velocity": {name: "Velocity", mime: "text/velocity", mode: "velocity", ext: ["vtl"]},
    "verilog": {name: "Verilog", mime: "text/x-verilog", mode: "verilog", ext: ["v"]},
    "vhdl":{name: "VHDL", mime: "text/x-vhdl", mode: "vhdl", ext: ["vhd", "vhdl"]},
    "xml":{name: "XML", mimes: ["application/xml", "text/xml"], mode: "xml", ext: ["xml", "xsl", "xsd"], alias: ["rss", "wsdl", "xsd"]},
    "xquery":{name: "XQuery", mime: "application/xquery", mode: "xquery", ext: ["xy", "xquery"]},
    "yaml":{name: "YAML", mime: "text/x-yaml", mode: "yaml", ext: ["yaml", "yml"], alias: ["yml"]},
    "z80":{name: "Z80", mime: "text/x-z80", mode: "z80", ext: ["z80"]},
    "mscgen":{name: "mscgen", mime: "text/x-mscgen", mode: "mscgen", ext: ["mscgen", "mscin", "msc"]},
    "xu":{name: "xu", mime: "text/x-xu", mode: "mscgen", ext: ["xu"]},
    "msgenny":{name: "msgenny", mime: "text/x-msgenny", mode: "mscgen", ext: ["msgenny"]}
};
